### ISSUE TITLE
Implement script code to pull Allocations state from chain

### ISSUE THREAD

**Issue by Quazia** [Giveth/planning-app#162]
This should be handled entirely in the script.js file of the allocations app. Right now the initial state isn't being loaded into the front end.

**Comment by topocount** [comment]
will create a branch for this as soon as 147 is pushed.

**Comment by topocount** [comment]
The initial state loads into the frontend after refreshing the whole page (hitting F5) after initial loading or after the state disappears, which can occur if browsing to another app for too long. 

Because of this behavior, it appears that the frontend's connection to messenger closes prematurely after enough idle time has passed. I can reliably stop the state from loading and then I can reliably get the state to reload again.

### Stopping State From Loading
Navigate to the allocations app after the apps intially loads in the browser for the first time, or after the cache is refreshed in Aragon's Settings Menu. 

### Getting the state to load
If existing state has not loaded, navigate to the app and refresh the page (F5 in most browsers)

### Stopping the State From Loading Again
After state loads in the Allocations App, click around to a few other apps and spend at least a minute away from the allocations App. Once the allocations app is reopened, the state will have disappeared.

**Comment by topocount** [comment]
@stellarmagnet please close this when you've verified it. Want to make sure it meets your discerning UI testing abilities :wink:
