### ISSUE TITLE
As a user I can login to github using their OAuth flow

### ISSUE THREAD

**Issue by Quazia** [Giveth/planning-app#73]
I will select sign in with github from the side-panel opened from previously clicking the New Project button.

**Comment by rkzel** [comment]
That's actually more complicated in our case. Usual scenario is based on having a central server that can keep application's secret key. User during OAuth process provides his credentials to GitHub's own auth form, gets special code, and then our application would use that code plus app's secret key to get the token (which can be used for all further operations). Unfortunately we have no backend server :) We could, for now, but the goal is to be decentralised, so we can as well prepare for it now. Therefore the correct way is for the user to generate "private token" in GitHub and use that as credential... Which is working nicely. And I'm going to leave it like this for the time being, until decided otherwise (I'm not aware of any good alternatives though).
